name: Extractor
on: [push, pull_request]
env:
  IS_CI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python Dependencies
        run: pip install -r extractor/requirements.txt
      - name: Lint
        run: make lint
        working-directory: ./extractor
      - name: Install APT Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: ffmpeg
      - name: Test
        run: make test
        working-directory: ./extractor
      - name: Coverage 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: extractor/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
      